<?php
$osszetetelListaItemArray = [
    'bankKoltseg' => [
        'kategoria' => 'Bank költség',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'befektetesek' => [
        'kategoria' => 'Befektetések',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'lakasElotak' => [
        'kategoria' => 'Lakás előtakarékosság',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'lakas' => [
        'kategoria' => 'Lakás, lakhatás',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'csalad' => [
        'kategoria' => 'Család',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'egeszseg' => [
        'kategoria' => 'Egészség, pihenés',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'szorakozas' => [
        'kategoria' => 'Szórakozás, ünnep',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'etkezes' => [
        'kategoria' => 'Étkezés',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'ado' => [
        'kategoria' => 'Adó, könyvelés',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'keszpenz' => [
        'kategoria' => 'Készpénzes költés',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'trade' => [
        'kategoria' => 'Tréd',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'ajandek' => [
        'kategoria' => 'Ajándék',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'kozlekedes' => [
        'kategoria' => 'Közlekedés, bringa, autó',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'internet' => [
        'kategoria' => 'Internet, telefon, gép',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'ruhazkodas' => [
        'kategoria' => 'Ruházkodás',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'onkepzes' => [
        'kategoria' => 'Önképzés, könyv',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ], 'onmegvalositas' => [
        'kategoria' => 'Önmegvalósítás',
        'aktual' => '280 000',
        'atlag' =>  '(280 000)'
    ],
];
