<?php
$current_data = file_get_contents('./data/savings/savingsCurrent.json');
$savingsCurrent = json_decode($current_data, true);

$osszetetelListaItemArray = [
    'bankKoltseg' => [
        'kategoria' => 'Bank költség',
        'aktual' => $savingsCurrent['bankKoltseg'],
        'atlag' =>  '(' . $savingsCurrent['bankKoltsegAvr'] .')'
    ], 'befektetesek' => [
        'kategoria' => 'Befektetések',
        'aktual' => $savingsCurrent['befektetesek'],
        'atlag' =>  '(' . $savingsCurrent['befektetesekAvr'] .')'
    ], 'lakasElotak' => [
        'kategoria' => 'Lakás előtakarékosság',
        'aktual' => $savingsCurrent['lakasElotak'],
        'atlag' =>  '(' . $savingsCurrent['lakasElotakAvr'] .')'
    ], 'lakas' => [
        'kategoria' => 'Lakás, lakhatás',
        'aktual' => $savingsCurrent['lakas'],
        'atlag' =>  '(' . $savingsCurrent['lakasAvr'] .')'
    ], 'csalad' => [
        'kategoria' => 'Család',
        'aktual' => $savingsCurrent['csalad'],
        'atlag' =>  '(' . $savingsCurrent['csaladAvr'] .')'
    ], 'egeszseg' => [
        'kategoria' => 'Egészség, pihenés',
        'aktual' => $savingsCurrent['egeszseg'],
        'atlag' =>  '(' . $savingsCurrent['egeszsegAvr'] .')'
    ], 'szorakozas' => [
        'kategoria' => 'Szórakozás, ünnep',
        'aktual' => $savingsCurrent['szorakozas'],
        'atlag' =>  '(' . $savingsCurrent['szorakozasAvr'] .')'
    ], 'etkezes' => [
        'kategoria' => 'Étkezés',
        'aktual' => $savingsCurrent['etkezes'],
        'atlag' =>  '(' . $savingsCurrent['etkezesAvr'] .')'
    ], 'ado' => [
        'kategoria' => 'Adó, könyvelés',
        'aktual' => $savingsCurrent['ado'],
        'atlag' =>  '(' . $savingsCurrent['adoAvr'] .')'
    ], 'keszpenz' => [
        'kategoria' => 'Készpénzes költés',
        'aktual' => $savingsCurrent['keszpenz'],
        'atlag' =>  '(' . $savingsCurrent['keszpenzAvr'] .')'
    ], 'trade' => [
        'kategoria' => 'Tréd',
        'aktual' => $savingsCurrent['trade'],
        'atlag' =>  '(' . $savingsCurrent['tradeAvr'] .')'
    ], 'ajandek' => [
        'kategoria' => 'Ajándék',
        'aktual' => $savingsCurrent['ajandek'],
        'atlag' =>  '(' . $savingsCurrent['ajandekAvr'] .')'
    ], 'kozlekedes' => [
        'kategoria' => 'Közlekedés, bringa, autó',
        'aktual' => $savingsCurrent['kozlekedes'],
        'atlag' =>  '(' . $savingsCurrent['kozlekedesAvr'] .')'
    ], 'internet' => [
        'kategoria' => 'Internet, telefon, gép',
        'aktual' => $savingsCurrent['internet'],
        'atlag' =>  '(' . $savingsCurrent['internetAvr'] .')'
    ], 'ruhazkodas' => [
        'kategoria' => 'Ruházkodás',
        'aktual' => $savingsCurrent['ruhazkodas'],
        'atlag' =>  '(' . $savingsCurrent['ruhazkodasAvr'] .')'
    ], 'onkepzes' => [
        'kategoria' => 'Önképzés, könyv',
        'aktual' => $savingsCurrent['onkepzes'],
        'atlag' =>  '(' . $savingsCurrent['onkepzesAvr'] .')'
    ], 'onmegvalositas' => [
        'kategoria' => 'Önmegvalósítás',
        'aktual' => $savingsCurrent['onmegvalositas'],
        'atlag' =>  '(' . $savingsCurrent['onmegvalositasAvr'] .')'
    ],
];
